apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Resources to include
resources:
  - deployment.yml
  - service.yml
  - curl.yml
  - configmap.yml

# Common labels applied to all resources
commonLabels:
  environment: workshop
  team: troubleshoot

# Name prefix for all resources
namePrefix: workshop-

# Images to use (can override here)
images:
  - name: nginx
    newTag: "1.21"
  - name: curlimages/curl
    newTag: "latest"